<?php

/**
 * @file
 * Primary module hooks for Custom Utility module.
 */

use Drupal\custom_utility\CommonService;
use Drupal\user\Entity\User;

/**
 * Implements hook_preprocess_HOOK() for node templates.
 */
function custom_utility_preprocess_node(&$variables) {
  // Check if this is a node page.
  if (isset($variables['node'])) {
    $form = null;
    // Get the current user.
    $current_user = User::load(\Drupal::currentUser()->id());
    // Check if the user has the "student" role.
    if ($current_user->hasRole('student')) {
      switch ($variables['node']->bundle()) {
        case 'course':
          // You can put your code here for handling the case where the user has the role.
          // Load the custom coure enrol form for course entity.
          $form = \Drupal::formBuilder()->getForm('Drupal\custom_utility\Form\CourseEnrolForm');
          // Get an instance of your common service.
          /** @var CommonService */
          $customService = \Drupal::service('custom_utility.common_service');
          $course_entity = $variables['node'];
          $variables['course_percentage'] = $customService->getCoursePercentage($course_entity);
          break;
        case 'lesson':
          // Load the custom lesson complete form for lesson entity.
          $form = \Drupal::formBuilder()->getForm('Drupal\custom_utility\Form\LessonCompleteForm');
          break;
        default:
          break;
      }
    }
    if ($form) {
      // Embed the form in the node's content if form present.
      $variables['content']['custom_form'] = $form;
    }
  }
}

/**
 * Implements hook_node_presave().
 */
function custom_utility_node_insert($node) {
  // Check if the node being saved is of the 'course' content type.
  if ($node->getType() == 'course') {
    // Load the referenced nodes (assuming you have a field named 'field_referenced_nodes').
    $referenced_nodes = $node->get('field_lessons')->referencedEntities();

    // Loop through the referenced nodes and update them.
    foreach ($referenced_nodes as $referenced_node) {
      // Check if the referenced node is of the desired content type.
      if ($referenced_node->getType() == 'lesson') {
        // Course reference is added here.
        $referenced_node->set('field_course', $node->id());
        $referenced_node->save();
      }
    }
  }
}
