<?php

/**
 * @file
 * Primary module hooks for Custom Utility module.
 */

use Drupal\Core\Link;
use Drupal\custom_utility\CommonService;
use Drupal\user\Entity\User;

/**
 * Implements hook_preprocess_HOOK() for node templates.
 */
function custom_utility_preprocess_node(&$variables) {
  // Check if this is a node page.
  if (isset($variables['node'])) {
    $form = null;
    // Get the current user.
    $current_user = User::load(\Drupal::currentUser()->id());
    $node = $variables['node'];
    // Check if the user has the "student" role.
    // Get an instance of your common service.
    /** @var CommonService */
    $common_service = \Drupal::service('custom_utility.common_service');
    if ($current_user->hasRole('student')) {
      switch ($node->bundle()) {
        case 'course':
          // You can put your code here for handling the case where the user has the role.
          // Load the custom coure enrol form for course entity.
          $form = \Drupal::formBuilder()->getForm('Drupal\custom_utility\Form\CourseEnrolForm');
          $course_entity = $node;
          $variables['course_percentage'] = $common_service->getCoursePercentage($course_entity);
          // Create a link to the node.
          $link = Link::createFromRoute(
            t('Get the certificate'),
            'custom_utility.controller',
            ['node' => $course_entity->id()],
            ['attributes' => ['class' => 'button--primary button']]
          );

          // Add the link to the form.
          $variables['get_certificate'] = [
            '#markup' => $link->toString(),
          ];
          break;
        case 'lesson':
          // Load the custom lesson complete form for lesson entity.
          $form = \Drupal::formBuilder()->getForm('Drupal\custom_utility\Form\LessonCompleteForm');
          break;
        default:
          break;
      }
    }
    if ($current_user->hasRole('instructor') && $node->bundle() == 'course') {
      // Load the custom lesson complete form for lesson entity.
      $form = \Drupal::formBuilder()->getForm('Drupal\custom_utility\Form\CourseGradeForm');
    }
    if ($node->bundle() == 'course') {
      // Add the average grade render array to the node's content.
      $variables['custom_utility__average_grade'] = $common_service->getAverageCourseGrade($node->id());
    }


    if ($form) {
      // Embed the form in the node's content if form present.
      $variables['content']['custom_form'] = $form;
    }
  }
}

/**
 * Implements hook_node_presave().
 */
function custom_utility_node_insert($node) {
  // Check if the node being saved is of the 'course' content type.
  if ($node->getType() == 'course') {
    // Load the referenced nodes (assuming you have a field named 'field_referenced_nodes').
    $referenced_nodes = $node->get('field_lessons')->referencedEntities();

    // Loop through the referenced nodes and update them.
    foreach ($referenced_nodes as $referenced_node) {
      // Check if the referenced node is of the desired content type.
      if ($referenced_node->getType() == 'lesson') {
        // Course reference is added here.
        $referenced_node->set('field_course', $node->id());
        $referenced_node->save();
      }
    }
  }
}
